App_Blog/urls.py
from django.urls import path
from . import views
app_name = 'App_Blog'
urlpatterns=[
    path('',views.BlogList.as_view(), name="blog_list"),
    path('write/',views.CreateBlog.as_view(), name="create_blog"),
    path('details/<str:slug>',views.blog_details, name="blog_details"),
    path('liked/<pk>',views.liked, name="liked_post"),
    path('unliked/<pk>',views.unliked, name="unliked_post"),
    path('my-blogs/',views.MyBlogs.as_view(), name="my_blogs"),
    path('edit/<pk>',views.UpdateBlog.as_view(), name="edit_blog"),
]

App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = 'App_Login'

urlpatterns=[
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change_profile/', views.user_change, name='user_change'),
    path('password/', views.pass_change, name='pass_change'),
    path('add-picture/', views.add_pro_pic, name='add_pro_pic'),
    path('change-picture/', views.change_pro_pic, name='change_pro_pic'),
]

Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.Index, name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous">
        </script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

        <title>{% block title_block %} Blogs {% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}"><img src="/media/logo.png" width="50px"></a>

            </li>
            {% if user.is_authenticated %}
            <div class="nav-item dropdown">
                <a href="" class="nav-link dropdown-toggle" id='navbardrop' data-toggle="dropdown">
                    @{{user.username}}
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'App_Blog:create_blog' %}">Write Blog</a>
                    <a class="dropdown-item" href="{% url 'App_Blog:my_blogs' %}">My Blog</a>
                    <a class="dropdown-item" href="{% url 'App_Login:profile' %}">Your Profile</a>
                    <hr>
                    <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>
                </div>
            </div>

            {% else %}
            <li class="nav-item ">
              <a class="nav-link" href="{% url 'App_Login:signup' %}">Sign Up</a>
            </li>
            <li class="nav-item ">
              <a class="nav-link" href="{% url 'App_Login:login' %}">Login</a>
            </li>

            {% endif %}
            </ul>

          </div>

        </nav>

        <div class="container" style="padding-top:20px">
            {% block body_block %}

            {% endblock%}

        </div>


    </body>
</html>